# Generated by Django 4.1.5 on 2023-01-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
